source "https://rubygems.org"

gem "fastlane"

# Add the Firebase App Distribution plugin
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
